package body A11y.Roles is
   pragma SPARK_Mode (On);

   Application_Name : aliased constant String := "application";
   Window_Name : aliased constant String := "window";
   Dialog_Name : aliased constant String := "dialog";
   Alert_Name : aliased constant String := "alert";
   Group_Name : aliased constant String := "group";
   Region_Name : aliased constant String := "region";
   Button_Name : aliased constant String := "button";
   Toggle_Button_Name : aliased constant String := "toggle-button";
   Check_Box_Name : aliased constant String := "check-box";
   Radio_Button_Name : aliased constant String := "radio-button";
   Combo_Box_Name : aliased constant String := "combo-box";
   List_Name : aliased constant String := "list";
   List_Item_Name : aliased constant String := "list-item";
   Tree_Name : aliased constant String := "tree";
   Tree_Item_Name : aliased constant String := "tree-item";
   Table_Name : aliased constant String := "table";
   Row_Name : aliased constant String := "row";
   Column_Name : aliased constant String := "column";
   Cell_Name : aliased constant String := "cell";
   Tab_List_Name : aliased constant String := "tab-list";
   Tab_Name : aliased constant String := "tab";
   Menu_Bar_Name : aliased constant String := "menu-bar";
   Menu_Name : aliased constant String := "menu";
   Menu_Item_Name : aliased constant String := "menu-item";
   Tool_Bar_Name : aliased constant String := "tool-bar";
   Text_Name : aliased constant String := "text";
   Static_Text_Name : aliased constant String := "static-text";
   Text_Field_Name : aliased constant String := "text-field";
   Search_Field_Name : aliased constant String := "search-field";
   Password_Field_Name : aliased constant String := "password-field";
   Slider_Name : aliased constant String := "slider";
   Spin_Button_Name : aliased constant String := "spin-button";
   Progress_Bar_Name : aliased constant String := "progress-bar";
   Scroll_Bar_Name : aliased constant String := "scroll-bar";
   Link_Name : aliased constant String := "link";
   Image_Name : aliased constant String := "image";
   Heading_Name : aliased constant String := "heading";
   Separator_Name : aliased constant String := "separator";
   Status_Name : aliased constant String := "status";
   Tooltip_Name : aliased constant String := "tooltip";
   Document_Name : aliased constant String := "document";
   Canvas_Name : aliased constant String := "canvas";
   Custom_Name : aliased constant String := "custom";

   function Metadata (Item : Role) return Role_Metadata is
     (case Item is
        when Application =>
          (Stable_Name => Application_Name'Access,
           Text_Entry => False,
           Surface => True,
           Focus => Focusable_Surface,
           Selection => Not_Selectable),
        when Window =>
          (Stable_Name => Window_Name'Access,
           Text_Entry => False,
           Surface => True,
           Focus => Focusable_Surface,
           Selection => Not_Selectable),
        when Dialog =>
          (Stable_Name => Dialog_Name'Access,
           Text_Entry => False,
           Surface => True,
           Focus => Focusable_Surface,
           Selection => Not_Selectable),
        when Alert =>
          (Stable_Name => Alert_Name'Access,
           Text_Entry => False,
           Surface => True,
           Focus => Focusable_Surface,
           Selection => Not_Selectable),
        when Group =>
          (Stable_Name => Group_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Never_Focusable,
           Selection => Not_Selectable),
        when Region =>
          (Stable_Name => Region_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Never_Focusable,
           Selection => Not_Selectable),
        when Button =>
          (Stable_Name => Button_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Not_Selectable),
        when Toggle_Button =>
          (Stable_Name => Toggle_Button_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Not_Selectable),
        when Check_Box =>
          (Stable_Name => Check_Box_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Not_Selectable),
        when Radio_Button =>
          (Stable_Name => Radio_Button_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Not_Selectable),
        when Combo_Box =>
          (Stable_Name => Combo_Box_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Selection_Container),
        when List =>
          (Stable_Name => List_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Selection_Container),
        when List_Item =>
          (Stable_Name => List_Item_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Selectable_Item),
        when Tree =>
          (Stable_Name => Tree_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Selection_Container),
        when Tree_Item =>
          (Stable_Name => Tree_Item_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Selectable_Item),
        when Table =>
          (Stable_Name => Table_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Selection_Container),
        when Row =>
          (Stable_Name => Row_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Never_Focusable,
           Selection => Selectable_Item),
        when Column =>
          (Stable_Name => Column_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Never_Focusable,
           Selection => Not_Selectable),
        when Cell =>
          (Stable_Name => Cell_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Selectable_Item),
        when Tab_List =>
          (Stable_Name => Tab_List_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Selection_Container),
        when Tab =>
          (Stable_Name => Tab_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Selectable_Item),
        when Menu_Bar =>
          (Stable_Name => Menu_Bar_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Not_Selectable),
        when Menu =>
          (Stable_Name => Menu_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Not_Selectable),
        when Menu_Item =>
          (Stable_Name => Menu_Item_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Not_Selectable),
        when Tool_Bar =>
          (Stable_Name => Tool_Bar_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Never_Focusable,
           Selection => Not_Selectable),
        when Text =>
          (Stable_Name => Text_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Never_Focusable,
           Selection => Not_Selectable),
        when Static_Text =>
          (Stable_Name => Static_Text_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Never_Focusable,
           Selection => Not_Selectable),
        when Text_Field =>
          (Stable_Name => Text_Field_Name'Access,
           Text_Entry => True,
           Surface => False,
           Focus => Focusable_When_Text_Entry,
           Selection => Not_Selectable),
        when Search_Field =>
          (Stable_Name => Search_Field_Name'Access,
           Text_Entry => True,
           Surface => False,
           Focus => Focusable_When_Text_Entry,
           Selection => Not_Selectable),
        when Password_Field =>
          (Stable_Name => Password_Field_Name'Access,
           Text_Entry => True,
           Surface => False,
           Focus => Focusable_When_Text_Entry,
           Selection => Not_Selectable),
        when Slider =>
          (Stable_Name => Slider_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Not_Selectable),
        when Spin_Button =>
          (Stable_Name => Spin_Button_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Not_Selectable),
        when Progress_Bar =>
          (Stable_Name => Progress_Bar_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Never_Focusable,
           Selection => Not_Selectable),
        when Scroll_Bar =>
          (Stable_Name => Scroll_Bar_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Not_Selectable),
        when Link =>
          (Stable_Name => Link_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Not_Selectable),
        when Image =>
          (Stable_Name => Image_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Never_Focusable,
           Selection => Not_Selectable),
        when Heading =>
          (Stable_Name => Heading_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Never_Focusable,
           Selection => Not_Selectable),
        when Separator =>
          (Stable_Name => Separator_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Never_Focusable,
           Selection => Not_Selectable),
        when Status =>
          (Stable_Name => Status_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Never_Focusable,
           Selection => Not_Selectable),
        when Tooltip =>
          (Stable_Name => Tooltip_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Never_Focusable,
           Selection => Not_Selectable),
        when Document =>
          (Stable_Name => Document_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Not_Selectable),
        when Canvas =>
          (Stable_Name => Canvas_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Focusable_When_Interactive,
           Selection => Not_Selectable),
        when Custom =>
          (Stable_Name => Custom_Name'Access,
           Text_Entry => False,
           Surface => False,
           Focus => Never_Focusable,
           Selection => Not_Selectable));

   function Stable_Name (Item : Role) return String is
     (Metadata (Item).Stable_Name.all);

   function Is_Text_Entry (Item : Role) return Boolean is
     (Metadata (Item).Text_Entry);

   function Is_Surface (Item : Role) return Boolean is
     (Metadata (Item).Surface);

   function Focus_Behavior (Item : Role) return Role_Focus_Behavior is
     (Metadata (Item).Focus);

   function Selection_Behavior (Item : Role) return Role_Selection_Behavior is
     (Metadata (Item).Selection);

   function Is_Selection_Container (Item : Role) return Boolean is
     (Selection_Behavior (Item) = Selection_Container);

   function Is_Selectable_Item (Item : Role) return Boolean is
     (Selection_Behavior (Item) = Selectable_Item);

end A11y.Roles;
