with Ada.Containers.Vectors;
with Ada.Strings.Unbounded;

package A11y.Conformance is

   subtype UString is Ada.Strings.Unbounded.Unbounded_String;

   type Support_Level is
     (Exact,
      Equivalent,
      Approximate,
      Internal_Only,
      Unsupported);

   type Feature_Id is
     (Core_Role_Button,
      Core_Role_Application,
      Core_Role_Window,
      Core_Role_Dialog,
      Core_Role_Group,
      Core_Role_Region,
      Core_Role_Static_Text,
      Core_Role_Toggle_Button,
      Core_Role_Check_Box,
      Core_Role_Radio_Button,
      Core_Role_Progress_Bar,
      Core_Role_Spin_Button,
      Core_Role_Slider,
      Core_Role_List,
      Core_Role_List_Item,
      Core_Role_Tree,
      Core_Role_Tree_Item,
      Core_Role_Table,
      Core_Role_Row,
      Core_Role_Column,
      Core_Role_Cell,
      Core_Role_Combo_Box,
      Core_Role_Search_Field,
      Core_Role_Menu_Bar,
      Core_Role_Menu,
      Core_Role_Menu_Item,
      Core_Role_Tool_Bar,
      Core_Role_Tab_List,
      Core_Role_Tab,
      Core_Role_Tooltip,
      Core_Role_Heading,
      Core_Role_Document,
      Core_Role_Text,
      Core_Role_Link,
      Core_Role_Password_Field,
      Core_Role_Scroll_Bar,
      Core_Role_Separator,
      Core_Role_Alert,
      Core_Role_Popup_Dialog,
      Core_Role_Text_Field,
      Core_Role_Image,
      Core_Role_Status,
      Core_Role_Decorative_Image,
      Core_Role_Canvas,
      Core_Role_Custom,
      Core_Role_Metadata,
      Core_Lifecycle_Metadata,
      Core_Lifecycle_Transition,
      Lifecycle_Stale_Reference,
      Core_Exposure_Metadata,
      Core_Focus_Session,
      Core_State_Enabled,
      Core_State_Sensitive,
      Core_State_Visible,
      Core_State_Showing,
      Core_State_Focused,
      Core_State_Focusable,
      Core_State_Selected,
      Core_State_Selectable,
      Core_State_Checked,
      Core_State_Indeterminate,
      Core_State_Expanded,
      Core_State_Expandable,
      Core_State_Pressed,
      Core_State_Read_Only,
      Core_State_Editable,
      Core_State_Required,
      Core_State_Invalid,
      Core_State_Busy,
      Core_State_Modal,
      Core_State_Multi_Line,
      Core_State_Multi_Selectable,
      Core_State_Visited,
      Core_State_Offscreen,
      Core_State_Defunct,
      Core_State_Active,
      Core_State_Metadata,
      Core_State_Derivation,
      Core_State_Validation,
      Core_Capability_Action,
      Core_Capability_Text,
      Core_Capability_Editable_Text,
      Core_Capability_Value,
      Core_Capability_Selection,
      Core_Capability_Table,
      Core_Capability_Document,
      Core_Capability_Image,
      Core_Capability_Relation,
      Core_Capability_Live_Region,
      Core_Capability_Surface,
      Core_Capability_Metadata,
      Core_Provider_Contract,
      Core_Geometry_Visibility,
      Core_Geometry_Region,
      Core_Node_Key_Registry,
      Core_Property_Role,
      Core_Property_State_Set,
      Core_Property_Name,
      Core_Property_Visible_Title,
      Core_Property_Description,
      Core_Property_Help_Text,
      Core_Property_Placeholder,
      Core_Property_Value_Text,
      Core_Property_Keyboard_Shortcut,
      Core_Property_Semantic_Identifier,
      Core_Property_Locale,
      Core_Property_Orientation,
      Core_Property_Set_Position,
      Core_Property_Set_Size,
      Core_Property_Hierarchical_Level,
      Core_Property_Heading_Level,
      Core_Property_Landmark,
      Core_Property_Bounds,
      Core_Property_Typed_Results,
      Core_Property_Status_Mapping,
      Core_Property_Metadata,
      Actions_Activate,
      Actions_Press,
      Actions_Toggle,
      Actions_Expand,
      Actions_Collapse,
      Actions_Show_Menu,
      Actions_Dismiss,
      Actions_Increment,
      Actions_Decrement,
      Actions_Select_Item,
      Actions_Deselect,
      Actions_Clear_Selection,
      Actions_Open,
      Actions_Close,
      Actions_Scroll_Into_View,
      Actions_Set_Focus,
      Actions_Metadata,
      Actions_Preconditions,
      Relations_Metadata,
      Relations_Labelled_By,
      Relations_Label_For,
      Relations_Described_By,
      Relations_Description_For,
      Relations_Controlled_By,
      Relations_Controller_For,
      Relations_Flows_To,
      Relations_Flows_From,
      Relations_Member_Of,
      Relations_Details,
      Relations_Details_For,
      Relations_Active_Descendant,
      Relations_Error_Message,
      Relations_Error_For,
      Relations_Embedded_By,
      Relations_Embeds,
      Relations_Popup_For,
      Relations_Popup_Controlled_By,
      Relations_Resource_Limit,
      Relations_Session_Ownership,
      Value_Kind_Unknown,
      Value_Kind_Indeterminate,
      Value_Kind_Integer,
      Value_Kind_Decimal,
      Value_Kind_Floating,
      Value_Kind_Boolean,
      Value_Kind_Enumerated,
      Value_Access_Read_Only,
      Value_Access_Writable,
      Value_Metadata,
      Value_Basic,
      Value_Range,
      Value_Decimal_Exact,
      Value_Resource_Limit,
      Value_Precision_Loss,
      Selection_Metadata,
      Selection_Single,
      Selection_Multiple,
      Selection_Range,
      Selection_Direction,
      Selection_Select_All,
      Selection_Current_Item,
      Selection_Resource_Limit,
      Selection_Validation,
      Text_Metadata,
      Text_Range_Basic,
      Text_Edit_Request,
      Text_UTF16_Conversion,
      Text_Protected,
      Text_Resource_Limit,
      Table_Metadata,
      Table_Cell_Basic,
      Table_Cell_Span,
      Table_Current_Cell,
      Table_Sort_Metadata,
      Table_Virtual_Size,
      Table_Resource_Limit,
      Document_Metadata,
      Document_Heading_Level,
      Document_Landmark,
      Document_Resource_Limit,
      Image_Metadata,
      Image_Alternative_Text,
      Image_Caption,
      Image_Category,
      Image_Decorative,
      Image_Resource_Limit,
      Window_Surface_Metadata,
      Window_Surface_Kind_Name,
      Window_Surface_Modal,
      Window_Surface_State_Metadata,
      Window_Surface_Validation,
      Native_Identity_Object_Path,
      Native_Identity_Runtime_Id,
      Native_Object_Cache_Identity,
      Native_Object_Cache_Tombstone,
      Native_Object_Cache_Session_Scope,
      Native_Object_Cache_Node_Index,
      Native_Object_Cache_Resource_Limit,
      Native_Object_Cache_Generation,
      Native_Object_Cache_Mutation_Report,
      Native_Object_Registry_Generation,
      Native_Object_Registry_Drained_Reset,
      Native_Object_Registry_Mutation_Report,
      Native_Object_Export_Descriptor,
      Native_Object_Lifetime_Resource_Limit,
      Native_Value_Resource_Limit,
      Native_Runtime_Lifecycle,
      Native_Runtime_Generation,
      Native_Runtime_Lifecycle_Report,
      Native_Runtime_Probe_Failure_Stage,
      Native_Readiness_Boundary_Stage,
      Native_Readiness_Remaining_Evidence,
      Native_Runtime_Event_Application,
      Native_Runtime_Event_Preparation,
      Native_Runtime_Event_Preparation_Report,
      Native_Projection_Property,
      Native_Projection_Action,
      Native_Request_Action_Payload,
      Native_Projection_Relation,
      Native_Projection_Event_Source,
      Native_Event_Validation,
      Native_Event_Prepared_Status,
      Native_Event_Staging_Queue,
      Native_Event_Posting_Interest,
      Native_Event_Posting_Boundary,
      Native_Event_Exhaustive_Map,
      Native_Role_Exhaustive_Map,
      Native_Relation_Exhaustive_Map,
      Native_Callback_Gate,
      Native_Callback_Generation,
      Native_Boundary_Call_Context,
      Native_Boundary_Call_Kind,
      Native_Boundary_Return_Class,
      Native_Boundary_Status_Recording,
      Native_Boundary_Cancellation,
      Native_Boundary_Query_Cancellation,
      Native_Boundary_Tree_Cancellation,
      Native_Boundary_Component_Cancellation,
      Native_Boundary_Focus_Cancellation,
      Native_Boundary_Relation_Cancellation,
      Native_Boundary_Action_Call,
      Native_Boundary_Node_Action_Call,
      Native_Boundary_Query_Call,
      Native_Boundary_Node_Query_Call,
      Native_Boundary_Tree_Call,
      Native_Boundary_Node_Tree_Call,
      Native_Boundary_Component_Call,
      Native_Boundary_Node_Component_Call,
      Native_Boundary_Focus_Call,
      Native_Boundary_Node_Focus_Call,
      Native_Boundary_Relation_Call,
      Native_Boundary_Node_Relation_Call,
      Native_Boundary_Node_Call,
      Native_Boundary_Stale_Metadata,
      Native_Boundary_Error_Map,
      Native_Boundary_Identity_Admission,
      Native_Boundary_Request_Admission,
      Native_Boundary_Admission_Report,
      Native_Boundary_Native_Call_Report,
      Native_Boundary_Completion_Report,
      Native_Boundary_Release_Report,
      Native_Fixture_Root_Query,
      Native_Fixture_Root_Failure_Stage,
      Native_Fixture_Root_Child_Traversal,
      Native_Fixture_Root_Child_Count,
      Native_Fixture_Root_Second_Child,
      Native_Fixture_Child_Query,
      Native_Fixture_Child_Native_Object,
      Native_Fixture_Child_Parent_Navigation,
      Native_Fixture_Child_Native_Identity,
      Native_Fixture_Second_Child_Parent_Navigation,
      Native_Fixture_Second_Child_Native_Identity,
      Native_Fixture_Sibling_Order,
      Native_Fixture_Child_Stale_Id,
      Linux_ATSPI_Role_Map,
      Linux_ATSPI_State_Map,
      Linux_ATSPI_Object_Path,
      Linux_ATSPI_Error_Name_Map,
      Linux_ATSPI_Error_Name_Inverse_Map,
      Linux_ATSPI_Error_Name_Diagnostic,
      Linux_DBUS_Bus_Address,
      Linux_DBUS_Connection_Lifecycle,
      Linux_DBUS_Local_Channel_Adapter,
      Linux_DBUS_Local_Channel_Receive,
      Linux_DBUS_Auth_External,
      Linux_DBUS_Auth_Exchange,
      Linux_DBUS_Authenticated_Connect,
      Linux_DBUS_Hello,
      Linux_DBUS_Authenticated_Hello,
      Linux_DBUS_Registration_Completion,
      Linux_DBUS_Authenticated_Registration,
      Linux_DBUS_Address_Discovery,
      Linux_DBUS_Host_Environment_Startup,
      Linux_DBUS_A11y_Bus_Get_Address,
      Linux_DBUS_Authenticated_Get_Address,
      Linux_DBUS_Startup_Session_Discovery,
      Linux_DBUS_Startup_Controller,
      Linux_DBUS_Startup_Backend_Adapter,
      Linux_DBUS_Startup_Outgoing_Work,
      Linux_DBUS_Startup_Event_Loop_Interest,
      Linux_DBUS_Startup_Event_Loop_Operation,
      Linux_DBUS_Startup_Outgoing_Flush,
      Linux_DBUS_Backend_Session_Event_Loop_Step,
      Linux_DBUS_Backend_Session_Scheduler,
      Linux_DBUS_Backend_Session_Transport_Cycle_Scheduler,
      Linux_DBUS_Outgoing_Back_Pressure,
      Linux_DBUS_Startup_Pump_Readiness,
      Linux_DBUS_Startup_Pump,
      Linux_DBUS_Startup_Pump_Report,
      Linux_DBUS_Startup_Pump_Bounded_Report,
      Linux_DBUS_Startup_Pump_Bounds,
      Linux_DBUS_Startup_Registered_Pump,
      Linux_DBUS_Transport_Serve_Cycle,
      Linux_DBUS_Codec_Basic,
      Linux_DBUS_Unsupported_Value,
      Linux_DBUS_UInt32_Array_Value,
      Linux_DBUS_State_Set_UInt32_Array,
      Linux_DBUS_String_Array_Value,
      Linux_DBUS_Attribute_String_Array,
      Linux_DBUS_Cache_Interface_String_Array,
      Linux_DBUS_Object_Path_Array_Value,
      Linux_DBUS_Relation_Target_Object_Path_Array,
      Linux_DBUS_Resource_Limits,
      Linux_DBUS_Message_Envelope,
      Linux_DBUS_Method_Call_Envelope,
      Linux_DBUS_Method_Return_Payload,
      Linux_DBUS_Startup_Reply_Evidence,
      Linux_DBUS_Transport_Frame_Metadata,
      Linux_DBUS_Method_Call_Destination_Routing,
      Linux_DBUS_Transport_Frame_Bytes,
      Linux_DBUS_Transport_Frame_Send,
      Linux_DBUS_Transport_Packet,
      Linux_DBUS_Transport_Packet_Send,
      Linux_DBUS_Transport_Packet_Decode,
      Linux_DBUS_Transport_Envelope_Decode,
      Linux_DBUS_Method_Return_Decode,
      Linux_DBUS_Error_Return_Decode,
      Linux_DBUS_Error_Return_Diagnostic,
      Linux_DBUS_Startup_Error_Completion,
      Linux_DBUS_Incoming_Call_Decode,
      Linux_DBUS_Incoming_Packet_Classification,
      Linux_DBUS_Incoming_Packet_No_Dispatch,
      Linux_DBUS_Incoming_Packet_Dispatch,
      Linux_DBUS_Signal_Envelope,
      Linux_DBUS_Prepared_Signal_Envelope,
      Linux_DBUS_Signal_Envelope_Build_Report,
      Linux_DBUS_Method_Boundary,
      Linux_DBUS_Application_Registration,
      Linux_ATSPI_Live_Transport_Registration_Observed,
      Linux_ATSPI_Live_External_Client_Registered_Transport,
      Linux_ATSPI_Serving_Packet_Stale_Error_Queued,
      Linux_ATSPI_Serving_Packet_Stale_Error_Serialized,
      Linux_ATSPI_Serving_Packet_Stale_Error_Decoded,
      Linux_ATSPI_Serving_Packet_Stale_Error_Drained,
      Linux_ATSPI_Serving_Packet_Unsupported_Interface_Queued,
      Linux_ATSPI_Serving_Packet_Unsupported_Interface_Serialized,
      Linux_ATSPI_Serving_Packet_Unsupported_Interface_Decoded,
      Linux_ATSPI_Serving_Packet_Unsupported_Interface_Drained,
      Linux_ATSPI_Serving_Packet_Probe,
      Linux_ATSPI_Serving_Packet_Tree_Traversal,
      Linux_ATSPI_Serving_Packet_Property,
      Linux_ATSPI_Serving_Packet_Property_Map,
      Linux_ATSPI_Serving_Packet_Stale_Error,
      Linux_ATSPI_Serving_Packet_Unsupported_Interface,
      Linux_ATSPI_Serving_Packet_Malformed_Packet,
      Linux_ATSPI_Serving_Packet_Text_Payload_Limit,
      Linux_ATSPI_Session_Dispatch_Probe,
      Linux_ATSPI_Session_Dispatch_Boundary_Drained,
      Linux_ATSPI_Session_Dispatch_Loop_Report,
      Linux_ATSPI_Session_Bus_Probe,
      Linux_ATSPI_Session_Startup_Stage,
      Linux_ATSPI_Startup_Object_Path,
      Linux_ATSPI_Method_Router,
      Linux_ATSPI_Application_Id,
      Linux_ATSPI_Application_Metadata,
      Linux_ATSPI_Accessible_Role,
      Linux_ATSPI_Accessible_Application,
      Linux_ATSPI_Accessible_Interfaces,
      Linux_ATSPI_Accessible_Role_Name,
      Linux_ATSPI_Accessible_Localized_Role_Name,
      Linux_ATSPI_Accessible_State,
      Linux_ATSPI_Accessible_Name,
      Linux_ATSPI_Accessible_Description,
      Linux_ATSPI_Accessible_Child_Count,
      Linux_ATSPI_Accessible_Child_At,
      Linux_ATSPI_Accessible_Children,
      Linux_ATSPI_Accessible_Parent,
      Linux_ATSPI_Accessible_Index_In_Parent,
      Linux_ATSPI_Accessible_Relations,
      Linux_ATSPI_Component_Extents,
      Linux_ATSPI_Component_Contains,
      Linux_ATSPI_Component_Hit_Test,
      Linux_ATSPI_Component_Focus,
      Linux_ATSPI_Action_Count,
      Linux_ATSPI_Action_Name,
      Linux_ATSPI_Action_Invoke,
      Linux_ATSPI_Value_Current,
      Linux_ATSPI_Value_Range,
      Linux_ATSPI_Value_Set_Request,
      Linux_ATSPI_Selection_Count,
      Linux_ATSPI_Selection_Selected_Child,
      Linux_ATSPI_Selection_Request,
      Linux_ATSPI_Selection_Deselect_Child,
      Linux_ATSPI_Selection_Select_All,
      Linux_ATSPI_Selection_Clear_Selection,
      Linux_ATSPI_Text_Character_Count,
      Linux_ATSPI_Text_Range,
      Linux_ATSPI_Text_Caret,
      Linux_ATSPI_Text_Protected,
      Linux_ATSPI_Text_Edit_Request,
      Linux_ATSPI_Table_Dimensions,
      Linux_ATSPI_Table_Cell,
      Linux_ATSPI_Table_Cell_Span,
      Linux_ATSPI_Table_Current_Cell,
      Linux_ATSPI_Table_Sort_Metadata,
      Linux_ATSPI_Image_Description,
      Linux_ATSPI_Image_Size,
      Linux_ATSPI_Image_Decorative_Omission,
      Linux_ATSPI_Document_Locale,
      Linux_ATSPI_Document_Attributes,
      Linux_ATSPI_Document_Heading_Level,
      Linux_ATSPI_Document_Landmark,
      Linux_ATSPI_Surface_Metadata,
      Linux_ATSPI_Surface_Routing,
      Linux_ATSPI_Signal_Focus,
      Linux_ATSPI_Signal_Text,
      Linux_ATSPI_Signal_Lifecycle,
      Linux_ATSPI_Signal_Prepared_Publication,
      Linux_ATSPI_Signal_Build_Report,
      Linux_ATSPI_Cache_Node,
      Linux_ATSPI_Object_Registry,
      Linux_ATSPI_Object_Export_Descriptor,
      Linux_ATSPI_Live_External_Client,
      Linux_ATSPI_Live_External_Client_Traversal,
      Linux_ATSPI_Live_External_Client_Failure_Stage,
      Linux_ATSPI_Live_External_Client_Attributes,
      Linux_ATSPI_Live_External_Client_Protected_Value,
      Linux_ATSPI_Live_External_Client_Component,
      Linux_ATSPI_Live_External_Client_Action,
      Linux_ATSPI_Live_External_Client_Value,
      Linux_ATSPI_Live_External_Client_Selection,
      Linux_ATSPI_Live_External_Client_Text,
      Linux_ATSPI_Live_External_Client_Image,
      Linux_ATSPI_Live_External_Client_Document,
      Linux_ATSPI_Live_External_Client_Table,
      Linux_ATSPI_Live_External_Client_Surface,
      Linux_ATSPI_Live_External_Client_Live_Region,
      Windows_UIA_Control_Type,
      Windows_UIA_Core_Properties,
      Windows_UIA_Bounding_Rectangle,
      Windows_UIA_Textual_Properties,
      Windows_UIA_Metadata_Properties,
      Windows_UIA_Protected_Value_Text,
      Windows_UIA_Unsupported_Value,
      Windows_UIA_Action_Map,
      Windows_UIA_Pattern_Discovery,
      Windows_UIA_Action_Request,
      Windows_UIA_Set_Focus_Request,
      Windows_UIA_Open_Action,
      Windows_UIA_Scroll_Into_View_Action,
      Windows_UIA_Close_Action,
      Windows_UIA_Event_Map,
      Windows_UIA_Event_Details,
      Windows_UIA_Prepared_Event_Emission,
      Windows_UIA_Event_Build_Report,
      Windows_UIA_Prepared_Event_Routing,
      Windows_UIA_Prepared_Event_Boundary,
      Windows_UIA_Event_Posting_Admission,
      Windows_UIA_Event_Posting_Report,
      Windows_UIA_Event_Posting_Drain_Bounded,
      Windows_UIA_Hostile_Callback_Admission,
      Windows_UIA_Missing_Identity,
      Windows_UIA_Mismatched_Identity,
      Windows_UIA_Malformed_Identity,
      Windows_UIA_Text_Payload_Limit,
      Windows_UIA_Fragment_Navigation,
      Windows_UIA_Runtime_Id,
      Windows_UIA_Relation_Routing,
      Windows_UIA_Value_Routing,
      Windows_UIA_Value_Set_Request,
      Windows_UIA_Selection_Routing,
      Windows_UIA_Selection_Request,
      Windows_UIA_Selection_Select_All,
      Windows_UIA_Selection_Clear_Selection,
      Windows_UIA_Text_Routing,
      Windows_UIA_Text_Edit_Routing,
      Windows_UIA_Table_Routing,
      Windows_UIA_Image_Routing,
      Windows_UIA_Document_Routing,
      Windows_UIA_Surface_Routing,
      Windows_UIA_Request_Router,
      Windows_UIA_ABI_Surface,
      Windows_UIA_Provider_Boundary,
      Windows_UIA_Bridge_Audit,
      Windows_UIA_Native_Bridge_Binding,
      Windows_UIA_HResult_Map,
      Windows_UIA_HResult_Inverse_Map,
      Windows_UIA_HResult_Diagnostic,
      Windows_UIA_Provider_Registry,
      Windows_UIA_COM_Lifetime,
      Windows_UIA_COM_Export_Descriptor,
      Windows_UIA_COM_Live_Export,
      Windows_UIA_Public_Root_Export,
      Windows_UIA_Public_Root_Native_Identity,
      Windows_UIA_Host_Window_Root_Binding,
      Windows_UIA_COM_VTable_Descriptor,
      Windows_UIA_COM_Object_Export,
      Windows_UIA_COM_Live_Interface_Retain,
      Windows_UIA_COM_Live_Interface_Release,
      Windows_UIA_COM_Live_Released_Interface,
      Windows_UIA_COM_Live_Invalid_Interface_Frame,
      Windows_UIA_COM_Live_Invalid_Method_Frame,
      Windows_UIA_COM_Live_Interface_Method_Mismatch,
      Windows_UIA_COM_Live_Provider_Options,
      Windows_UIA_COM_Live_Host_Raw_Element_Provider,
      Windows_UIA_COM_Live_Pattern_Provider_Frame,
      Windows_UIA_COM_Live_Simple_Property_Frame,
      Windows_UIA_COM_Live_Bounding_Rectangle_Frame,
      Windows_UIA_COM_Live_Fragment_Action_Frame,
      Windows_UIA_COM_Live_Fragment_Navigate,
      Windows_UIA_COM_Live_Fragment_Last_Child_Frame,
      Windows_UIA_COM_Live_Fragment_Runtime_Id,
      Windows_UIA_COM_Live_Embedded_Fragment_Roots,
      Windows_UIA_COM_Live_Fragment_Root,
      Windows_UIA_COM_Live_Fragment_Root_Point,
      Windows_UIA_COM_Live_Fragment_Root_Focus,
      Windows_UIA_External_Client_Blocked_Probe,
      Windows_UIA_External_Client_Failure_Stage,
      Windows_UIA_Native_Values,
      MacOS_NSAX_Role,
      MacOS_NSAX_Core_Attributes,
      MacOS_NSAX_Frame_Attribute,
      MacOS_NSAX_Textual_Attributes,
      MacOS_NSAX_Metadata_Attributes,
      MacOS_NSAX_Protected_Value_Text,
      MacOS_NSAX_Unsupported_Value,
      MacOS_NSAX_Action_Map,
      MacOS_NSAX_Action_Discovery,
      MacOS_NSAX_Action_Request,
      MacOS_NSAX_Open_Action,
      MacOS_NSAX_Close_Action,
      MacOS_NSAX_Set_Focus_Action,
      MacOS_NSAX_Scroll_To_Visible_Action,
      MacOS_NSAX_Event_Map,
      MacOS_NSAX_Event_Details,
      MacOS_NSAX_Prepared_Event_Emission,
      MacOS_NSAX_Event_Build_Report,
      MacOS_NSAX_Prepared_Event_Routing,
      MacOS_NSAX_Prepared_Event_Boundary,
      MacOS_NSAX_Event_Posting_Admission,
      MacOS_NSAX_Event_Posting_Report,
      MacOS_NSAX_Event_Posting_Drain_Bounded,
      MacOS_NSAX_Hostile_Callback_Admission,
      MacOS_NSAX_Missing_Identity,
      MacOS_NSAX_Mismatched_Identity,
      MacOS_NSAX_Malformed_Identity,
      MacOS_NSAX_Text_Payload_Limit,
      MacOS_NSAX_Hierarchy,
      MacOS_NSAX_Element_Id,
      MacOS_NSAX_Relation_Routing,
      MacOS_NSAX_Value_Routing,
      MacOS_NSAX_Value_Set_Request,
      MacOS_NSAX_Selection_Routing,
      MacOS_NSAX_Selection_Request,
      MacOS_NSAX_Selection_Select_All,
      MacOS_NSAX_Selection_Clear_Selection,
      MacOS_NSAX_Text_Routing,
      MacOS_NSAX_Text_Edit_Routing,
      MacOS_NSAX_Table_Routing,
      MacOS_NSAX_Image_Routing,
      MacOS_NSAX_Document_Routing,
      MacOS_NSAX_Surface_Routing,
      MacOS_NSAX_Request_Router,
      MacOS_NSAX_ABI_Surface,
      MacOS_NSAX_Provider_Boundary,
      MacOS_NSAX_Bridge_Audit,
      MacOS_NSAX_Native_Bridge_Binding,
      MacOS_NSAX_Virtual_Element_Bridge,
      MacOS_NSAX_Native_Status_Map,
      MacOS_NSAX_Native_Status_Inverse_Map,
      MacOS_NSAX_Native_Status_Diagnostic,
      MacOS_NSAX_Element_Registry,
      MacOS_NSAX_Element_Lifetime,
      MacOS_NSAX_Element_Export_Descriptor,
      MacOS_NSAX_Public_Root_Export,
      MacOS_NSAX_Public_Root_Native_Identity,
      MacOS_NSAX_Public_Root_Hit_Test_Frame,
      MacOS_NSAX_Public_Root_Focused_Element_Frame,
      MacOS_NSAX_Public_Root_Notification_Frame,
      MacOS_NSAX_Main_Thread_Binding,
      MacOS_NSAX_Native_View_Binding,
      MacOS_NSAX_Attribute_Names,
      MacOS_NSAX_Selector_Attribute_Value,
      MacOS_NSAX_Selector_Children_Frame,
      MacOS_NSAX_Selector_Child_At_Index_Frame,
      MacOS_NSAX_Selector_Attribute_Value_Frame,
      MacOS_NSAX_Selector_Attribute_Settable_Frame,
      MacOS_NSAX_Selector_Action_Frame,
      MacOS_NSAX_Selector_Unsupported,
      MacOS_NSAX_Selector_Main_Thread_Gate,
      MacOS_NSAX_Registered_Method_Family_Mismatch,
      MacOS_NSAX_Released_Boundary,
      MacOS_NSAX_External_Client_Blocked_Probe,
      MacOS_NSAX_External_Client_Failure_Stage,
      MacOS_NSAX_Native_Values,
      Diagnostics_Metadata,
      Diagnostics_Result_Mapping,
      Diagnostics_Field_Bounds,
      Diagnostics_Localization,
      Backend_Diagnostics_Bounded,
      Backend_Null_Event_Limit,
      Results_Metadata,
      Resource_Limits_Defaults,
      Resource_Limits_Metadata,
      Resource_Limits_Validation,
      Backend_Selection_Default,
      Backend_Selection_Runtime_Override,
      Backend_Selection_Fallback,
      Backend_Selection_Disabled,
      Backend_State_Metadata,
      Backend_Kind_Metadata,
      Backend_Disabled_Lifecycle,
      Backend_Native_Scaffold,
      Backend_Native_Target_Resolution,
      Backend_Native_Transport_Admission,
      Backend_Native_Transport_Status,
      Backend_Transport_Unavailable,
      Backend_Native_Transport_Generation,
      Backend_Native_Transport_Transition_Report,
      Backend_Native_Deterministic_Shutdown,
      Backend_Native_Publication_Preparation,
      Events_Metadata,
      Events_Envelope,
      Events_Timestamp_Order,
      Events_Classification,
      Events_Node_Created,
      Events_Focus_Changed,
      Events_Node_Destroyed,
      Events_Node_Attached,
      Events_Node_Detached,
      Events_Child_Added,
      Events_Child_Removed,
      Events_Children_Reordered,
      Events_Subtree_Rebuilt,
      Events_Property_Changed,
      Events_State_Changed,
      Events_Bounds_Changed,
      Events_Active_Descendant_Changed,
      Events_Selection_Changed,
      Events_Current_Item_Changed,
      Events_Value_Changed,
      Events_Range_Changed,
      Events_Text_Inserted,
      Events_Text_Removed,
      Events_Text_Replaced,
      Events_Caret_Moved,
      Events_Text_Selection_Changed,
      Events_Text_Attributes_Changed,
      Events_Row_Inserted,
      Events_Row_Removed,
      Events_Column_Inserted,
      Events_Column_Removed,
      Events_Cell_Changed,
      Events_Window_Opened,
      Events_Window_Closed,
      Events_Window_Activated,
      Events_Window_Deactivated,
      Events_Document_Loaded,
      Events_Document_Closed,
      Events_Announcement_Requested,
      Events_Live_Region,
      Events_Live_Region_Changed,
      Events_Relation_Added,
      Events_Relation_Removed,
      Events_Relation_Targets_Changed,
      Events_Live_Region_Payload,
      Live_Region_Metadata,
      Live_Region_Relevance,
      Live_Region_Backend_Routing,
      Events_Text_Payload,
      Events_Property_Payload,
      Events_Property_Orientation,
      Events_Property_Set_Position,
      Events_Property_Set_Size,
      Events_Property_Hierarchical_Level,
      Events_State_Payload,
      Events_Relation_Payload,
      Events_Bounds_Payload,
      Events_Focus_Payload,
      Events_Node_Reference_Payload,
      Events_Value_Payload,
      Events_Selection_Payload,
      Events_Tree_Payload,
      Events_Table_Payload,
      Events_Document_Payload,
      Events_Window_Payload,
      Events_Session_Notification,
      Events_Backend_Pump,
      Events_Backend_Pump_Report,
      Events_Subscription_Filter,
      Events_Subscription_Bounds,
      Tree_Ownership,
      Tree_Attachment_Validation,
      Tree_Exposure_Projection,
      Tree_Mutation_Event_Order,
      Tree_Traversal_Limit,
      Lifecycle_Tombstone,
      Dispatcher_Call_Metadata,
      Dispatcher_Timeout_Classification,
      Dispatcher_Call_Accounting,
      Dispatcher_Cancellation,
      Dispatcher_Reentrancy,
      Null_Backend_Event_Order);

   type Declaration is record
      Feature        : Feature_Id := Core_Role_Button;
      Backend        : UString;
      Support        : Support_Level := Unsupported;
      Native_Mapping : UString;
      Test_Id        : UString;
   end record;

   package Declaration_Vectors is new Ada.Containers.Vectors
     (Index_Type => Positive, Element_Type => Declaration);

   function Dotted_Name (Feature : Feature_Id) return String
   with
      SPARK_Mode => On,
      Global => null;

   procedure Add
     (Items          : in out Declaration_Vectors.Vector;
      Feature        : Feature_Id;
      Backend        : String;
      Support        : Support_Level;
      Native_Mapping : String := "";
      Test_Id        : String := "");

   function Support_For
     (Items   : Declaration_Vectors.Vector;
      Feature : Feature_Id;
      Backend : String)
      return Support_Level;

   function Is_Production_Support (Level : Support_Level) return Boolean
   with
     SPARK_Mode => On,
     Global => null,
     Post =>
       Is_Production_Support'Result =
         (Level in Exact | Equivalent | Approximate);

   function Is_Internal_Or_Unsupported
     (Level : Support_Level)
      return Boolean
   with
      SPARK_Mode => On,
      Global => null,
      Post =>
        Is_Internal_Or_Unsupported'Result =
          (Level in Internal_Only | Unsupported);

   function Support_Rank (Level : Support_Level) return Natural
   with
      SPARK_Mode => On,
      Global => null,
      Post =>
        (case Level is
           when Unsupported => Support_Rank'Result = 0,
           when Internal_Only => Support_Rank'Result = 1,
           when Approximate => Support_Rank'Result = 2,
           when Equivalent => Support_Rank'Result = 3,
           when Exact => Support_Rank'Result = 4);

   function At_Least
     (Level     : Support_Level;
      Threshold : Support_Level)
      return Boolean
   with
      SPARK_Mode => On,
      Global => null,
      Post =>
        At_Least'Result =
          (Support_Rank (Level) >= Support_Rank (Threshold));

   function Is_Native_Backend (Backend : String) return Boolean
   with
     SPARK_Mode => On,
     Global => null,
     Post =>
       Is_Native_Backend'Result =
         (Backend = "AT-SPI"
          or else Backend = "UIA"
          or else Backend = "NSAccessibility");

   function Native_Production_Claims_Require_Evidence
     (Items                     : Declaration_Vectors.Vector;
      Native_Evidence_Available : Boolean)
      return Boolean;

   function Null_Backend_Declarations return Declaration_Vectors.Vector;
   function Disabled_Backend_Declarations return Declaration_Vectors.Vector;
   function Linux_ATSPI_Declarations return Declaration_Vectors.Vector;
   function Windows_UIA_Declarations return Declaration_Vectors.Vector;
   function MacOS_NSAccessibility_Declarations return Declaration_Vectors.Vector;
   function All_Declarations return Declaration_Vectors.Vector;

end A11y.Conformance;
